name: "Version Logic action"
description: "Uses Ibexa-specific rules to output previous tag for comparing"
author: "Petro Kurbatskyi"
inputs:
  currentTag:
    required: true
    description: "Current tag"
    default: "v1.0.0"
  prevFullTag:
    required: false
    description: "Previous full release tag"
outputs:
  previousTag:
    description: "Output from the action"
runs:
  using: "docker"
  image: "docker://ghcr.io/ibexa/version-logic-action:v1.3.2"
